# forecast.py
# Baseline demand forecast + MAPE scoring
# Runs AFTER config_demand.csv is generated by demand.py

import pandas as pd
import numpy as np
from pathlib import Path
import sys

sys.path.append(str(Path(__file__).parent))
from config import CONFIG_NAMES, PLANNING_WEEKS

PROCESSED_DIR = Path(__file__).parent.parent / "data" / "processed"
DEMAND_FILE   = PROCESSED_DIR / "config_demand.csv"


def load_demand() -> pd.DataFrame:
    """Load config_demand.csv generated by demand.py"""
    return pd.read_csv(DEMAND_FILE)


def naive_forecast(df: pd.DataFrame) -> pd.DataFrame:
    """
    Naive baseline: forecast for week t = actual value at week t-1.
    Returns DataFrame with columns: week, config, actual, forecast
    """
    # YOUR CODE HERE
    raise NotImplementedError("naive_forecast() not implemented yet")


def moving_average_forecast(df: pd.DataFrame, window: int = 4) -> pd.DataFrame:
    """
    Moving average forecast with given window size.
    Returns DataFrame with columns: week, config, actual, forecast
    """
    # YOUR CODE HERE
    raise NotImplementedError("moving_average_forecast() not implemented yet")


def mape(actual: pd.Series, forecast: pd.Series) -> float:
    """
    Mean Absolute Percentage Error.
    Returns MAPE as a percentage (e.g. 12.4 means 12.4%).
    """
    # YOUR CODE HERE
    raise NotImplementedError("mape() not implemented yet")


def score_all(df: pd.DataFrame) -> pd.DataFrame:
    """
    Run all forecast methods and return MAPE for each config + method.
    """
    # YOUR CODE HERE
    raise NotImplementedError("score_all() not implemented yet")


if __name__ == "__main__":
    df = load_demand()
    print(f"Loaded {len(df)} rows of demand data")
    print(df.head(8))
